import 'dart:io';

import 'package:flutter/services.dart' show rootBundle;
import 'package:path/path.dart' as p;

import '../models.dart';
import 'project_service.dart';

/// Phase 1: offline equivalent of `flutter create` (writes the project
/// skeleton + CI files directly; android/ folder is generated by GitHub
/// Actions with the real `flutter create`).
class BootstrapService {
  static const Map<String, String> _deps = {
    'riverpod': '  flutter_riverpod: ">=2.5.0 <4.0.0"',
    'bloc': '  flutter_bloc: ">=8.1.0 <10.0.0"',
    'provider': '  provider: ">=6.1.0 <7.0.0"',
    'getx': '  get: ">=4.6.0 <5.0.0"',
    'none': '',
  };

  static Future<String> _tpl(String name) =>
      rootBundle.loadString('assets/templates/$name');

  static String pascal(String snake) {
    final parts = snake.split('_').where((s) => s.isNotEmpty);
    return parts.map((s) => s[0].toUpperCase() + s.substring(1)).join();
  }

  static String title(String snake) {
    final parts = snake.split('_').where((s) => s.isNotEmpty);
    return parts.map((s) => s[0].toUpperCase() + s.substring(1)).join(' ');
  }

  static String _fill(String t, Map<String, String> v) {
    var o = t;
    v.forEach((k, val) {
      o = o.replaceAll('{{$k}}', val);
    });
    return o;
  }

  static Future<void> run({
    required String root,
    required WizardConfig cfg,
    required void Function(String) log,
  }) async {
    if (!await ProjectService.canWrite(root)) {
      throw ProjectException('Folder me write access nahi hai.');
    }
    if (!await ProjectService.isEmptyDir(root)) {
      throw ProjectException('Folder empty nahi hai.');
    }
    final ps = ProjectService(root);

    final platforms = <String>{...cfg.platforms, 'android'}.toList()..sort();
    final platformsCsv = platforms.join(',');
    final values = <String, String>{
      'NAME': cfg.name,
      'ORG': cfg.org,
      'TITLE': title(cfg.name),
      'CLASS': pascal(cfg.name),
      'PLATFORMS': platformsCsv,
      'ANDROID_LANG': cfg.androidLang,
      'IOS_LANG': cfg.iosLang,
      'STATE': cfg.state,
      'LAYOUT': cfg.layout,
      'DEPS': _deps[cfg.state] ?? '',
    };

    log('flutter create --project-name ${cfg.name} --org ${cfg.org} '
        '--platforms $platformsCsv .');
    log('(offline mode: project files direct likh raha hoon)');

    final mainTpl = cfg.state == 'riverpod'
        ? 'main_riverpod.dart.tpl'
        : (cfg.state == 'getx' ? 'main_getx.dart.tpl' : 'main_plain.dart.tpl');

    final files = <String, String>{
      'pubspec.yaml': 'pubspec.yaml.tpl',
      'lib/main.dart': mainTpl,
      '.gitignore': 'gitignore.tpl',
      'README.md': 'README.md.tpl',
      '.github/workflows/build-apk.yml': 'build-apk.yml.tpl',
      'gradle_fix/fix.gradle': 'fix.gradle.tpl',
    };
    for (final e in files.entries) {
      final text = _fill(await _tpl(e.value), values);
      await ps.writeFile(e.key, text);
      log('created ${e.key}');
    }

    final dirs = cfg.layout == 'feature'
        ? [
            'lib/core',
            'lib/shared',
            'lib/features/home/data',
            'lib/features/home/domain',
            'lib/features/home/presentation',
          ]
        : ['lib/core', 'lib/data', 'lib/domain', 'lib/presentation'];
    for (final d in dirs) {
      await ps.writeFile(p.join(d, '.gitkeep'), '');
      log('created $d/');
    }

    if (cfg.state != 'none') {
      log('dependency added for ${cfg.state}');
    }
    log('Project ready: ${Directory(root).path}');
  }
}
